### ISSUE TITLE
Example With Demo Notebooks That Require Dependencies

### ISSUE THREAD

**Issue by psychemedia** [binder-examples/setup.py#2]
One of the things I've noticed with many repos that are Binderised to show off notebooks that demonstrate how to run a package defined by the repo is that the demo notebook has additional requirements over and above those required to build the original package.

It would be useful for this repo to demonstrate how to [use a `binder/` directory](https://mybinder.readthedocs.io/en/latest/using.html) to "hide" any additional `requirements.txt` file (or other package including files) needed to run any notebook examples.

I guess that including the `binder/` directory will prevent any build actions being take on the `setup.py` file, so I guess a `binder/postBuild` file would aslo be required to build install the package from the top-level?

I've also noticed that some repos have pretty complete `setup.py` files that install versioned packages that may clash with packages installed as part of the Binder process (e.g. one build I tried because of a `certifi` package version incompatability). This may be a result of the repo developer adding in requirements to install and run a notebook server of their own for running demo notebooks, which is not strictly a requirement of the package.  In such a case, could the package build process could be completed in a separate environment and then the built package copied over to the Binder running environment? (Though I guess in turn that might require some package requirements being duplicated in the `binder/` directory.)

**Comment by choldgraf** [comment]
oops, sorry we missed this issue (the `binder-examples` repos aren't checked as often as the repo2docker/binder/etc ones). I see the problem here, and wonder if `setup.py` should somehow be treated as a special case even if `binder/` exists, since (to my knowledge) there's no reason to put `setup.py` anywhere outside the root of the repo. Do you think you could open an issue about this in the repo2docker repo so we can discuss there?
